# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rumba_msg/BatteryStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BatteryStatus(genpy.Message):
  _md5sum = "8553ab09064a977637e06a24726e1227"
  _type = "rumba_msg/BatteryStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 percentage_battery
float64 location_x
float64 location_y
float64 orientation_theta
bool brushes_up
string debug_message
"""
  __slots__ = ['percentage_battery','location_x','location_y','orientation_theta','brushes_up','debug_message']
  _slot_types = ['int64','float64','float64','float64','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       percentage_battery,location_x,location_y,orientation_theta,brushes_up,debug_message

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BatteryStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.percentage_battery is None:
        self.percentage_battery = 0
      if self.location_x is None:
        self.location_x = 0.
      if self.location_y is None:
        self.location_y = 0.
      if self.orientation_theta is None:
        self.orientation_theta = 0.
      if self.brushes_up is None:
        self.brushes_up = False
      if self.debug_message is None:
        self.debug_message = ''
    else:
      self.percentage_battery = 0
      self.location_x = 0.
      self.location_y = 0.
      self.orientation_theta = 0.
      self.brushes_up = False
      self.debug_message = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_q3dB().pack(_x.percentage_battery, _x.location_x, _x.location_y, _x.orientation_theta, _x.brushes_up))
      _x = self.debug_message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.percentage_battery, _x.location_x, _x.location_y, _x.orientation_theta, _x.brushes_up,) = _get_struct_q3dB().unpack(str[start:end])
      self.brushes_up = bool(self.brushes_up)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.debug_message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.debug_message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_q3dB().pack(_x.percentage_battery, _x.location_x, _x.location_y, _x.orientation_theta, _x.brushes_up))
      _x = self.debug_message
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.percentage_battery, _x.location_x, _x.location_y, _x.orientation_theta, _x.brushes_up,) = _get_struct_q3dB().unpack(str[start:end])
      self.brushes_up = bool(self.brushes_up)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.debug_message = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.debug_message = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_q3dB = None
def _get_struct_q3dB():
    global _struct_q3dB
    if _struct_q3dB is None:
        _struct_q3dB = struct.Struct("<q3dB")
    return _struct_q3dB
