cobot:
  # Publish all the joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers and setup PID
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link__link_1
    pid: {p: 1000, i: 100, d: 10}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_1__link_2
    pid: {p: 1200, i: 120, d: 80}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_2__link_3
    pid: {p: 1000, i: 100, d: 70}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_3__link_4
    pid: {p: 1000, i: 100, d: 50}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_4__link_5
    pid: {p: 2000, i: 150, d: 80}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_5__link_6
    pid: {p: 100, i: 50, d: 0}

  gripper_controller_right:
    type: effort_controllers/JointPositionController
    joint: finger_right_joint
    pid: {p: 2500, i: 10, d: 10}