cobot:
  # Publish all the joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers and setup PID
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link__link_1
    pid: {p: 700, i: 50, d: 70}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: link_1__link_2
    pid: {p: 700, i: 50, d: 70}